project:
  type: website
  output-dir: docs

website:
  title: "Projeto Germinação"
 
  
  navbar:
   left:
      - text: Introdução ao R
        href: arquivo1.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

