project:
  type: website
  output-dir: docs

website:
  title: "Projeto Germinação"
 
  navbar:
   pinned: true
   left:
   - text: Pré-visualização
     href: arquivo1.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

